# Cleaning customers data

In [76]:
import pandas as pd 

customers = pd.read_csv("customers.csv")
customers.info()
customers

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             97263 non-null   str
 8   customer_since     100400 non-null  str
dtypes: int64(1), str(8)
memory usage: 6.9 MB

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,NaN,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,"28,803.42",2013-02-10
...,...,...,...,...,...,...,...,...,...
100395,28691,Zanele,Pillay,27,Gauteng,Pretoria,Employed,8793.76,2022-04-07
100396,3743,Thabo,Molefe,41,KwaZulu-Natal,Durban,Retired,18720.9,2025-09-04
100397,91741,Ethan,Dlamini,18,Gauteng,Midrand,Employed,28779.63,2014-08-25
100398,2999,Emma,Botha,41,Gauteng,Pretoria,Retired,14252.29,2014-02-20
100399,17834,Ethan,Mokoena,29,Northern Cape,Kimberley,Self-employed,30125.07,2024-12-07

In [122]:

#Converting customer_since data type to datetime and fixing date format
#customers['customer_since'] = customers['customer_since'].str.replace("-", "/")

customers['customer_since'] = pd.to_datetime(
    customers['customer_since'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26
100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [78]:
#Changing income data type and removing "R" and "," and spaces

customers['income'] = customers['income'].str.replace(",", "")
customers['income'] = customers['income'].str.replace(" ", "")
customers['income'] = customers['income'].str.replace("R", "")
customers['income'] = customers['income'].astype(float)
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             97263 non-null   float64
 8   customer_since     100180 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 6.9 MB

In [79]:
customers.employment_status = customers.employment_status.str.strip()
customers.employment_status = customers.employment_status.str.capitalize()

customers.employment_status.unique()

<StringArray>
['Employed', nan, 'Retired', 'Student', 'Self-employed', 'Unemployed', 'Nan']
Length: 7, dtype: str

In [80]:
# replacing null values with"Nan"
import numpy as np
customers = customers.replace(np.nan,"Nan")

In [81]:

# Replace "unknown" variations with missing values
customers['age'] = customers['age'].replace(
    ['unknown', 'Unknown', 'UNKNOWN', 'unkown', -4, 150, 999, 0],
    np.nan
)

# Convert to numeric
customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

# Fill missing ages with the median
customers['age'] = customers['age'].fillna(customers['age'].median())

# Convert to integer
customers['age'] = customers['age'].astype(int)


customers['age'].unique()

customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  int64
 4   province           100400 non-null  str
 5   city               100400 non-null  str
 6   employment_status  100400 non-null  str
 7   income             100400 non-null  object
 8   customer_since     100400 non-null  object
dtypes: int64(2), object(2), str(5)
memory usage: 6.9+ MB

In [82]:
#Removing duplicates

customers = customers.drop_duplicates()

customers[customers.duplicated() == True]

Empty DataFrame
Columns: [customer_id, first_name, last_name, age, province, city, employment_status, income, customer_since]
Index: []

In [83]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18 00:00:00
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21 00:00:00
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,28803.42,2013-10-02 00:00:00
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,eastern cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26 00:00:00
100392,89556,Lerato,Botha,33,KwaZulu-Natal,Durban,Unemployed,21132.74,2021-08-28 00:00:00
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19 00:00:00
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17 00:00:00

In [84]:
customers.city = customers.city.str.strip()
#removing the white and space bar spaces 
customers.city = customers.city.str.replace(r'\s+', ' ', regex=True)
customers.city = customers.city.str.title()

customers.city.unique()

<StringArray>
[    'Bloemfontein',         'Mbombela',       'Rustenburg',
           'Durban',          'Tzaneen',         'Pretoria',
      'Thohoyandou',           'George',            'Paarl',
          'Midrand',     'Johannesburg', 'Pietermaritzburg',
        'Cape Town',          'Kuruman',        'Bethlehem',
      'East London',         'Gqeberha',          'Mthatha',
        'Kimberley',        'Polokwane',     'Richards Bay',
           'Soweto',     'Stellenbosch',       'Emalahleni',
         'Mahikeng',           'Welkom',       'Klerksdorp',
         'Upington',          'Secunda',              'Nan']
Length: 30, dtype: str

In [85]:
customers.province = customers.province.str.strip()
customers.province = customers.province.str.replace(r'\s+', ' ', regex=True)
customers.province = customers.province.str.title()

customers.province.unique()

<StringArray>
[   'Free State',    'Mpumalanga',    'North West', 'Kwazulu-Natal',
       'Limpopo',       'Gauteng',  'Western Cape', 'Northern Cape',
  'Eastern Cape']
Length: 9, dtype: str

In [86]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18 00:00:00
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21 00:00:00
4,5,Emma,MOLEFE,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02 00:00:00
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26 00:00:00
100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28 00:00:00
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19 00:00:00
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17 00:00:00

In [123]:
customers.info()

<class 'pandas.DataFrame'>
Index: 100090 entries, 0 to 100394
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100090 non-null  int64
 1   first_name         100090 non-null  str
 2   last_name          100090 non-null  str
 3   age                100090 non-null  int64
 4   province           100090 non-null  str
 5   city               100090 non-null  str
 6   employment_status  100090 non-null  str
 7   income             100090 non-null  object
 8   customer_since     99870 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(2), object(1), str(5)
memory usage: 7.6+ MB

# Cleaning Branches

In [153]:
import pandas as pd 

branches = pd.read_csv("branches.csv")
branches.info()
branches

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    250 non-null    int64
 1   branch_name  250 non-null    str
 2   province     247 non-null    str
 3   city         249 non-null    str
 4   branch_type  250 non-null    str
dtypes: int64(1), str(4)
memory usage: 9.9 KB

     branch_id        branch_name      province          city branch_type
0            1  Mzansi Branch 001  Western Cape     Cape Town    Suburban
1            2  Mzansi Branch 002    Mpumalanga    Emalahleni       Rural
2            3  Mzansi Branch 003       Limpopo     Polokwane       Urban
3            2  Mzansi Branch 004  Eastern Cape      Gqeberha       Urban
4            5  Mzansi Branch 005  Eastern Cape   East London       Urban
..         ...                ...           ...           ...         ...
245        246  Mzansi Branch 246  Western Cape  Stellenbosch       Urban
246        247  Mzansi Branch 247    Mpumalanga      MBOMBELA       Urban
247        248  Mzansi Branch 248  Eastern Cape   East London    Suburban
248        249  Mzansi Branch 249    North West    Klerksdorp       Urban
249        250  Mzansi Branch 250  Western Cape  Stellenbosch       Urban

[250 rows x 5 columns]

In [154]:
#Replacing all null values with "Nan"
branches = branches.replace(np.nan,"Nan")

In [155]:


branches.province = branches.province.str.strip()
#removing the white and space bar spaces 
branches.province = branches.province.str.replace(r'\s+', ' ', regex=True)
branches.province = branches.province.str.title()
branches.province.unique()

<StringArray>
[ 'Western Cape',    'Mpumalanga',       'Limpopo',  'Eastern Cape',
    'North West',           'Nan',       'Gauteng',    'Free State',
 'Northern Cape', 'Kwazulu-Natal']
Length: 10, dtype: str

In [156]:
branches.city = branches.city.str.strip()
#removing the white and space bar spaces
branches.city = branches.city.str.replace(r'\s+', ' ', regex=True)
branches.city = branches.city.str.title()

branches.city.unique()

<StringArray>
[       'Cape Town',       'Emalahleni',        'Polokwane',
         'Gqeberha',      'East London',       'Rustenburg',
           'George',         'Mbombela',     'Johannesburg',
        'Bethlehem',        'Kimberley',          'Secunda',
         'Mahikeng',           'Welkom',         'Pretoria',
     'Bloemfontein',          'Kuruman',      'Thohoyandou',
       'Klerksdorp', 'Pietermaritzburg',            'Paarl',
           'Soweto',         'Upington',          'Midrand',
          'Mthatha',           'Durban',     'Richards Bay',
     'Stellenbosch',          'Tzaneen',              'Nan']
Length: 30, dtype: str

In [157]:
#Checking duplicates
branches[branches.duplicated() == True]

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [158]:
#Ch
branches.branch_type = branches.branch_type.str.strip()
#removing the white and space bar spaces
branches.branch_type = branches.branch_type.str.replace(r'\s+', ' ', regex=True)
branches.branch_type = branches.branch_type.str.title()
branches.branch_type.unique()

<StringArray>
['Suburban', 'Rural', 'Urban']
Length: 3, dtype: str

In [159]:
#branches[branches.city.isin(['Mbombela', 'Bethlehem', 'Rustenburg'])]
# branches[(branches['city'] == 'Mbombela') & (branches['province'].isna())].fillna("Mpumalanga")
# branches[(branches['city'] == 'Rustenburg') & (branches['province'].isna())].fillna("North West")
# branches[(branches['city'] == 'Bethlehem') & (branches['province'].isna())].fillna("Free State")

#Filling the null provinces using their cities
province_map = {

'Mbombela': 'Mpumalanga',

'Rustenburg': 'North West',

'Bethlehem': 'Free State'

}

for city, province in province_map.items():
 branches.loc[

(branches['city'] == city) & (branches['province'].isna()),

'province'

] = province

In [160]:


mode_city = branches.loc[
branches['province'] == 'Northern Cape',
'city'
].mode()
mode_city

branches[(branches['province'] == 'Northern Cape') & (branches['city'].isna())].fillna(mode_city)

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [161]:
branches[(branches['province'] == 'Northern Cape') & (branches['city'].isna())].fillna(mode_city)

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [165]:
branches

     branch_id        branch_name      province          city branch_type
0            1  Mzansi Branch 001  Western Cape     Cape Town    Suburban
1            2  Mzansi Branch 002    Mpumalanga    Emalahleni       Rural
2            3  Mzansi Branch 003       Limpopo     Polokwane       Urban
3            2  Mzansi Branch 004  Eastern Cape      Gqeberha       Urban
4            5  Mzansi Branch 005  Eastern Cape   East London       Urban
..         ...                ...           ...           ...         ...
245        246  Mzansi Branch 246  Western Cape  Stellenbosch       Urban
246        247  Mzansi Branch 247    Mpumalanga      Mbombela       Urban
247        248  Mzansi Branch 248  Eastern Cape   East London    Suburban
248        249  Mzansi Branch 249    North West    Klerksdorp       Urban
249        250  Mzansi Branch 250  Western Cape  Stellenbosch       Urban

[250 rows x 5 columns]