# Cleaning customers data

In [99]:
import pandas as pd 

customers = pd.read_csv("customers.csv")
customers.info()
customers

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             97263 non-null   str
 8   customer_since     100400 non-null  str
dtypes: int64(1), str(8)
memory usage: 6.9 MB

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,NaN,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,"28,803.42",2013-02-10
...,...,...,...,...,...,...,...,...,...
100395,28691,Zanele,Pillay,27,Gauteng,Pretoria,Employed,8793.76,2022-04-07
100396,3743,Thabo,Molefe,41,KwaZulu-Natal,Durban,Retired,18720.9,2025-09-04
100397,91741,Ethan,Dlamini,18,Gauteng,Midrand,Employed,28779.63,2014-08-25
100398,2999,Emma,Botha,41,Gauteng,Pretoria,Retired,14252.29,2014-02-20
100399,17834,Ethan,Mokoena,29,Northern Cape,Kimberley,Self-employed,30125.07,2024-12-07

In [133]:

#Converting customer_since data type to datetime and fixing date format
#customers['customer_since'] = customers['customer_since'].str.replace("-", "/")

customers['customer_since'] = pd.to_datetime(
    customers['customer_since'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26
100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [112]:
#Changing income data type and removing "R" and "," and spaces

customers['income'] = customers['income'].str.replace(",", "")
customers['income'] = customers['income'].str.replace(" ", "")
customers['income'] = customers['income'].str.replace("R", "")
customers['income'] = customers['income'].astype(float)
customers.info()

<class 'pandas.DataFrame'>
Index: 100091 entries, 0 to 100394
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100091 non-null  int64
 1   first_name         100091 non-null  str
 2   last_name          100091 non-null  str
 3   age                100091 non-null  str
 4   province           100091 non-null  str
 5   city               99487 non-null   str
 6   employment_status  96988 non-null   str
 7   income             96959 non-null   float64
 8   customer_since     99871 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 7.6 MB

In [128]:
customers.employment_status = customers.employment_status.str.strip()
customers.employment_status = customers.employment_status.str.capitalize()

customers.employment_status.unique()

<StringArray>
['Employed', 'Nan', 'Retired', 'Student', 'Self-employed', 'Unemployed']
Length: 6, dtype: str

In [ ]:
# replacing null values with"Nan"
import numpy as np
customers = customers.replace(np.nan,"Nan")

In [ ]:

# Replace "unknown" variations with missing values
customers['age'] = customers['age'].replace(
    ['unknown', 'Unknown', 'UNKNOWN', 'unkown', -4, 150, 999, 0],
    np.nan
)

# Convert to numeric
customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

# Fill missing ages with the median
customers['age'] = customers['age'].fillna(customers['age'].median())

# Convert to integer
customers['age'] = customers['age'].astype(int)


customers['age'].unique()

array([42, 49, 34, 35, 33, 29, 59, 39, 18, 47, 23, 43, 37, 24, 51, 27, 53,
       21, 31, 25, 20, 56, 48, 54, 28, 61, 19, 67, 55, 41, 46, 44, 40, 58,
       38, 32, 36, 60, 62, 30, 26, 66, 45, 22, 70, 81, 57, 64, 50, 52, 78,
       73, 63, 69, 74, 68, 65, 72, 83, 76, 71, 77, 80, 79, 85, 75, 82, 84])

In [104]:
#Removing duplicates

customers = customers.drop_duplicates()

customers[customers.duplicated() == True]

Empty DataFrame
Columns: [customer_id, first_name, last_name, age, province, city, employment_status, income, customer_since]
Index: []

In [114]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,NaN,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,eastern cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,NaN,2016-12-26
100392,89556,Lerato,Botha,33,KwaZulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [129]:
customers.city = customers.city.str.strip()
customers.city = customers.city.str.replace(r'\s+', ' ', regex=True)
customers.city = customers.city.str.title()

customers.city.unique()

<StringArray>
[    'Bloemfontein',         'Mbombela',       'Rustenburg',
           'Durban',          'Tzaneen',         'Pretoria',
      'Thohoyandou',           'George',            'Paarl',
          'Midrand',     'Johannesburg', 'Pietermaritzburg',
        'Cape Town',          'Kuruman',        'Bethlehem',
      'East London',         'Gqeberha',          'Mthatha',
        'Kimberley',        'Polokwane',     'Richards Bay',
           'Soweto',     'Stellenbosch',       'Emalahleni',
         'Mahikeng',           'Welkom',       'Klerksdorp',
         'Upington',          'Secunda',              'Nan']
Length: 30, dtype: str

In [119]:
customers.province = customers.province.str.strip()
customers.province = customers.province.str.replace(r'\s+', ' ', regex=True)
customers.province = customers.province.str.title()

customers.province.unique()

<StringArray>
[   'Free State',    'Mpumalanga',    'North West', 'Kwazulu-Natal',
       'Limpopo',       'Gauteng',  'Western Cape', 'Northern Cape',
  'Eastern Cape']
Length: 9, dtype: str

In [130]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18 00:00:00
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21 00:00:00
4,5,Emma,MOLEFE,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02 00:00:00
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26 00:00:00
100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28 00:00:00
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19 00:00:00
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17 00:00:00