# Cleaning customers data

In [106]:
import pandas as pd 

customers = pd.read_csv("data/raw/customers.csv")
customers.info()
customers

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             97263 non-null   str
 8   customer_since     100400 non-null  str
dtypes: int64(1), str(8)
memory usage: 6.9 MB

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,NaN,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,"28,803.42",2013-02-10
...,...,...,...,...,...,...,...,...,...
100395,28691,Zanele,Pillay,27,Gauteng,Pretoria,Employed,8793.76,2022-04-07
100396,3743,Thabo,Molefe,41,KwaZulu-Natal,Durban,Retired,18720.9,2025-09-04
100397,91741,Ethan,Dlamini,18,Gauteng,Midrand,Employed,28779.63,2014-08-25
100398,2999,Emma,Botha,41,Gauteng,Pretoria,Retired,14252.29,2014-02-20
100399,17834,Ethan,Mokoena,29,Northern Cape,Kimberley,Self-employed,30125.07,2024-12-07

In [117]:

#Converting customer_since data type to datetime and fixing date format
#customers['customer_since'] = customers['customer_since'].str.replace("-", "/")

customers['customer_since'] = pd.to_datetime(
    customers['customer_since'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             100400 non-null  str
 8   customer_since     100400 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 6.9 MB

In [109]:
customers['customer_since'] = customers['customer_since'].fillna(pd.Timestamp('1900-01-01'))

In [ ]:
customers.income = customers.income.fillna('0.0')

In [118]:
#Changing income data type and removing "R" and "," and spaces

customers['income'] = customers['income'].str.replace(",", "")
customers['income'] = customers['income'].str.replace(" ", "")
customers['income'] = customers['income'].str.replace("R", "")
customers['income'] = customers['income'].astype(float)
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  str
 4   province           100400 non-null  str
 5   city               99796 non-null   str
 6   employment_status  97293 non-null   str
 7   income             100400 non-null  float64
 8   customer_since     100400 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 6.9 MB

In [119]:
customers.employment_status = customers.employment_status.str.strip()
customers.employment_status = customers.employment_status.str.capitalize()

customers.employment_status.unique()

<StringArray>
['Employed', nan, 'Retired', 'Student', 'Self-employed', 'Unemployed', 'Nan']
Length: 7, dtype: str

In [120]:
# replacing null values with"Nan"
import numpy as np
customers = customers.replace(np.nan,"Nan")

In [121]:

# Replace "unknown" variations with missing values
customers['age'] = customers['age'].replace(
    ['unknown', 'Unknown', 'UNKNOWN', 'unkown', -4, 150, 999, 0],
    np.nan
)

# Convert to numeric
customers['age'] = pd.to_numeric(customers['age'], errors='coerce')

# Fill missing ages with the median
customers['age'] = customers['age'].fillna(customers['age'].median())

# Convert to integer
customers['age'] = customers['age'].astype(int)


customers['age'].unique()

customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100400 entries, 0 to 100399
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100400 non-null  int64
 1   first_name         100400 non-null  str
 2   last_name          100400 non-null  str
 3   age                100400 non-null  int64
 4   province           100400 non-null  str
 5   city               100400 non-null  str
 6   employment_status  100400 non-null  str
 7   income             100400 non-null  float64
 8   customer_since     100400 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 6.9 MB

In [122]:
#Removing duplicates

customers = customers.drop_duplicates()

customers[customers.duplicated() == True]

Empty DataFrame
Columns: [customer_id, first_name, last_name, age, province, city, employment_status, income, customer_since]
Index: []

In [123]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,MOLEFE,33,KwaZulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,eastern cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,NOAH,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26
100392,89556,Lerato,Botha,33,KwaZulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [124]:

customers.first_name = customers.first_name.str.title()

customers.last_name = customers.last_name.str.title()
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,KwaZulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,Molefe,33,KwaZulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,eastern cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26
100392,89556,Lerato,Botha,33,KwaZulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [125]:
customers.city = customers.city.str.strip()
#removing the white and space bar spaces 
customers.city = customers.city.str.replace(r'\s+', ' ', regex=True)
customers.city = customers.city.str.title()

customers.city.unique()

<StringArray>
[    'Bloemfontein',         'Mbombela',       'Rustenburg',
           'Durban',          'Tzaneen',         'Pretoria',
      'Thohoyandou',           'George',            'Paarl',
          'Midrand',     'Johannesburg', 'Pietermaritzburg',
        'Cape Town',          'Kuruman',        'Bethlehem',
      'East London',         'Gqeberha',          'Mthatha',
        'Kimberley',        'Polokwane',     'Richards Bay',
           'Soweto',     'Stellenbosch',       'Emalahleni',
         'Mahikeng',           'Welkom',       'Klerksdorp',
         'Upington',          'Secunda',              'Nan']
Length: 30, dtype: str

In [126]:
customers.province = customers.province.str.strip()
customers.province = customers.province.str.replace(r'\s+', ' ', regex=True)
customers.province = customers.province.str.title()

customers.province.unique()

<StringArray>
[   'Free State',    'Mpumalanga',    'North West', 'Kwazulu-Natal',
       'Limpopo',       'Gauteng',  'Western Cape', 'Northern Cape',
  'Eastern Cape']
Length: 9, dtype: str

In [127]:
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21
4,5,Emma,Molefe,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...
100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03
100390,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26
100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100394,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [148]:
customers.info()

<class 'pandas.DataFrame'>
Index: 100090 entries, 0 to 100394
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        100090 non-null  int64
 1   first_name         100090 non-null  str
 2   last_name          100090 non-null  str
 3   age                100090 non-null  int64
 4   province           100090 non-null  str
 5   city               100090 non-null  str
 6   employment_status  100090 non-null  str
 7   income             100090 non-null  float64
 8   customer_since     100090 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 7.6 MB

In [128]:
customers.to_csv("data/processed/cleanedCustomers2.csv")

# Cleaning Branches

In [62]:
import pandas as pd 

branches = pd.read_csv("data/raw/branches.csv")
branches.info()
branches

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    250 non-null    int64
 1   branch_name  250 non-null    str
 2   province     247 non-null    str
 3   city         249 non-null    str
 4   branch_type  250 non-null    str
dtypes: int64(1), str(4)
memory usage: 9.9 KB

     branch_id        branch_name      province          city branch_type
0            1  Mzansi Branch 001  Western Cape     Cape Town    Suburban
1            2  Mzansi Branch 002    Mpumalanga    Emalahleni       Rural
2            3  Mzansi Branch 003       Limpopo     Polokwane       Urban
3            2  Mzansi Branch 004  Eastern Cape      Gqeberha       Urban
4            5  Mzansi Branch 005  Eastern Cape   East London       Urban
..         ...                ...           ...           ...         ...
245        246  Mzansi Branch 246  Western Cape  Stellenbosch       Urban
246        247  Mzansi Branch 247    Mpumalanga      MBOMBELA       Urban
247        248  Mzansi Branch 248  Eastern Cape   East London    Suburban
248        249  Mzansi Branch 249    North West    Klerksdorp       Urban
249        250  Mzansi Branch 250  Western Cape  Stellenbosch       Urban

[250 rows x 5 columns]

In [ ]:
#Replacing all null values with "Nan"
branches = branches.replace(np.nan,"Nan")
branches.info()

     branch_id        branch_name      province          city branch_type
0            1  Mzansi Branch 001  Western Cape     Cape Town    Suburban
1            2  Mzansi Branch 002    Mpumalanga    Emalahleni       Rural
2            3  Mzansi Branch 003       Limpopo     Polokwane       Urban
3            2  Mzansi Branch 004  Eastern Cape      Gqeberha       Urban
4            5  Mzansi Branch 005  Eastern Cape   East London       Urban
..         ...                ...           ...           ...         ...
245        246  Mzansi Branch 246  Western Cape  Stellenbosch       Urban
246        247  Mzansi Branch 247    Mpumalanga      Mbombela       Urban
247        248  Mzansi Branch 248  Eastern Cape   East London    Suburban
248        249  Mzansi Branch 249    North West    Klerksdorp       Urban
249        250  Mzansi Branch 250  Western Cape  Stellenbosch       Urban

[250 rows x 5 columns]

In [64]:


branches.province = branches.province.str.strip()
#removing the white and space bar spaces 
branches.province = branches.province.str.replace(r'\s+', ' ', regex=True)
branches.province = branches.province.str.title()
branches.province.unique()

<StringArray>
[ 'Western Cape',    'Mpumalanga',       'Limpopo',  'Eastern Cape',
    'North West',           'Nan',       'Gauteng',    'Free State',
 'Northern Cape', 'Kwazulu-Natal']
Length: 10, dtype: str

In [65]:
branches.city = branches.city.str.strip()
#removing the white and space bar spaces
branches.city = branches.city.str.replace(r'\s+', ' ', regex=True)
branches.city = branches.city.str.title()

branches.city.unique()

<StringArray>
[       'Cape Town',       'Emalahleni',        'Polokwane',
         'Gqeberha',      'East London',       'Rustenburg',
           'George',         'Mbombela',     'Johannesburg',
        'Bethlehem',        'Kimberley',          'Secunda',
         'Mahikeng',           'Welkom',         'Pretoria',
     'Bloemfontein',          'Kuruman',      'Thohoyandou',
       'Klerksdorp', 'Pietermaritzburg',            'Paarl',
           'Soweto',         'Upington',          'Midrand',
          'Mthatha',           'Durban',     'Richards Bay',
     'Stellenbosch',          'Tzaneen',              'Nan']
Length: 30, dtype: str

In [66]:
#Checking duplicates
branches[branches.duplicated() == True]

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [67]:
#Ch
branches.branch_type = branches.branch_type.str.strip()
#removing the white and space bar spaces
branches.branch_type = branches.branch_type.str.replace(r'\s+', ' ', regex=True)
branches.branch_type = branches.branch_type.str.title()
branches.branch_type.unique()

<StringArray>
['Suburban', 'Rural', 'Urban']
Length: 3, dtype: str

In [68]:
#branches[branches.city.isin(['Mbombela', 'Bethlehem', 'Rustenburg'])]
# branches[(branches['city'] == 'Mbombela') & (branches['province'].isna())].fillna("Mpumalanga")
# branches[(branches['city'] == 'Rustenburg') & (branches['province'].isna())].fillna("North West")
# branches[(branches['city'] == 'Bethlehem') & (branches['province'].isna())].fillna("Free State")

#Filling the null provinces checking their cities
province_map = {

'Mbombela': 'Mpumalanga',

'Rustenburg': 'North West',

'Bethlehem': 'Free State'

}

for city, province in province_map.items():
 branches.loc[

(branches['city'] == city) & (branches['province'].isna()),

'province'

] = province

In [69]:

# Check the mode of cities in the Northern Cape
mode_city = branches.loc[
branches['province'] == 'Northern Cape',
'city'
].mode()
mode_city

branches[(branches['province'] == 'Northern Cape') & (branches['city'].isna())].fillna(mode_city)

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [70]:
#Filling the null city in Northern Cape with the mode of the cities in Northern cape
branches[(branches['province'] == 'Northern Cape') & (branches['city'].isna())].fillna(mode_city)

Empty DataFrame
Columns: [branch_id, branch_name, province, city, branch_type]
Index: []

In [71]:
branches.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    250 non-null    int64
 1   branch_name  250 non-null    str
 2   province     250 non-null    str
 3   city         250 non-null    str
 4   branch_type  250 non-null    str
dtypes: int64(1), str(4)
memory usage: 9.9 KB

In [72]:
branches.to_csv("data/processed/cleanedBranches.csv")

# Cleaning Accounts

In [133]:
import pandas as pd 

accounts = pd.read_csv("data/raw/accounts.csv")
accounts.info()
accounts

<class 'pandas.DataFrame'>
RangeIndex: 125375 entries, 0 to 125374
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_id      125375 non-null  int64
 1   customer_id     124756 non-null  str
 2   account_type    124715 non-null  str
 3   branch_id       125375 non-null  int64
 4   account_status  124735 non-null  str
 5   opened_date     125375 non-null  str
dtypes: int64(2), str(4)
memory usage: 5.7 MB

,account_id,customer_id,account_type,branch_id,account_status,opened_date
0,1,74688,Business,150,Active,2017-06-28
1,2,21183,Savings,54,Active,2021-01-26
2,3,93719,Cheque,164,Active,2023-01-13
3,4,6909,cheque,36,active,2017-12-30
4,5,45524,Cheque,86,Active,2021-02-21
...,...,...,...,...,...,...
125370,89439,85991,Savings,229,Active,2024-08-27
125371,21550,57898,Savings,206,Active,2016-10-18
125372,2529,31546,Savings,21,Dormant,2022-05-06
125373,116956,2412,Business,164,Dormant,2021-11-25
125374,34908,89262,Cheque,214,Dormant,2023-11-15

In [134]:
#Droping the row with null customer_id

accounts = accounts.drop(
    accounts[accounts['customer_id'].isna()].index
)

accounts[accounts['customer_id'].isna()]

Empty DataFrame
Columns: [account_id, customer_id, account_type, branch_id, account_status, opened_date]
Index: []

In [135]:

#Fixing the CustomerID
accounts[accounts['customer_id'] == 'INVALID_CUST_0000210']

,account_id,customer_id,account_type,branch_id,account_status,opened_date
786,787,INVALID_CUST_0000210,Cheque,76,Active,2016-12-07

In [136]:
#Fixing the CustomerID
accounts['customer_id'] = accounts['customer_id'].str.replace(
'INVALID_CUST_', '',
regex=False
)

In [137]:
accounts['customer_id'] = accounts['customer_id'].astype('int64')
accounts.info()

<class 'pandas.DataFrame'>
Index: 124756 entries, 0 to 125374
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_id      124756 non-null  int64
 1   customer_id     124756 non-null  int64
 2   account_type    124101 non-null  str
 3   branch_id       124756 non-null  int64
 4   account_status  124119 non-null  str
 5   opened_date     124756 non-null  str
dtypes: int64(3), str(3)
memory usage: 6.7 MB

In [138]:
accounts['opened_date'] = pd.to_datetime(
    accounts['opened_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
    
).fillna(pd.Timestamp("1900-01-01"))
accounts.info()

<class 'pandas.DataFrame'>
Index: 124756 entries, 0 to 125374
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_id      124756 non-null  int64
 1   customer_id     124756 non-null  int64
 2   account_type    124101 non-null  str
 3   branch_id       124756 non-null  int64
 4   account_status  124119 non-null  str
 5   opened_date     124756 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 6.7 MB

In [140]:
# replacing null values with"Nan"
import numpy as np
accounts = accounts.replace(np.nan,"Nan")

accounts.info()

<class 'pandas.DataFrame'>
Index: 124756 entries, 0 to 125374
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_id      124756 non-null  int64
 1   customer_id     124756 non-null  int64
 2   account_type    124756 non-null  str
 3   branch_id       124756 non-null  int64
 4   account_status  124756 non-null  str
 5   opened_date     124756 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 6.7 MB

In [141]:
accounts.account_type = accounts.account_type.str.strip()

accounts.account_type = accounts.account_type.str.title()

accounts.account_type.unique()

<StringArray>
['Business', 'Savings', 'Cheque', 'Credit', 'Nan']
Length: 5, dtype: str

In [142]:
accounts.account_status = accounts.account_status.str.strip()

accounts.account_status = accounts.account_status.str.title()
accounts.account_status.unique()

<StringArray>
['Active', 'Dormant', 'Closed', 'Open', 'Nan', 'Terminated']
Length: 6, dtype: str

In [143]:
#Checking duplicates
accounts[accounts.duplicated() == True]

,account_id,customer_id,account_type,branch_id,account_status,opened_date
125000,58886,33232,Savings,222,Active,2018-07-21
125001,106269,14324,Savings,81,Active,2022-05-07
125002,103202,53155,Credit,210,Closed,2022-01-04
125003,11742,49296,Savings,117,Active,2024-12-18
125004,121303,84598,Credit,109,Active,2024-01-26
...,...,...,...,...,...,...
125370,89439,85991,Savings,229,Active,2024-08-27
125371,21550,57898,Savings,206,Active,2016-10-18
125372,2529,31546,Savings,21,Dormant,2022-06-05
125373,116956,2412,Business,164,Dormant,2021-11-25
125374,34908,89262,Cheque,214,Dormant,2023-11-15

In [144]:
#Removing duplicates

accounts = accounts.drop_duplicates()

accounts[accounts.duplicated() == True]

Empty DataFrame
Columns: [account_id, customer_id, account_type, branch_id, account_status, opened_date]
Index: []

In [ ]:
accounts.to_csv("data/processed/cleanedAccounts2.csv", index=False)

In [147]:
accounts.info()

<class 'pandas.DataFrame'>
Index: 124401 entries, 0 to 125363
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_id      124401 non-null  int64
 1   customer_id     124401 non-null  int64
 2   account_type    124401 non-null  str
 3   branch_id       124401 non-null  int64
 4   account_status  124401 non-null  str
 5   opened_date     124401 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 6.6 MB

# Merging Customers and Accounts

In [85]:
import pandas as pd 
accounts = pd.read_csv("data/processed/cleanedAccounts.csv")
customers = pd.read_csv("data/processed/cleanedCustomers.csv")

cus_acc = customers.merge(accounts, on="customer_id",how="inner")
cus_acc = cus_acc.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y'])
cus_acc

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since,account_id,account_type,branch_id,account_status,opened_date
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00,7374,Cheque,68,Dormant,2024-03-25 00:00:00
1,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00,77521,Cheque,6,Active,2016-04-17 00:00:00
2,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00,76314,Cheque,63,Dormant,2023-01-01 00:00:00
3,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00,108831,Savings,78,Active,2016-03-24 00:00:00
4,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18 00:00:00,73522,Business,147,Nan,2018-08-25 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124522,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00,32628,Business,145,Active,2025-03-29 00:00:00
124523,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00,73251,Savings,1,Active,2016-01-02 00:00:00
124524,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00,90163,Cheque,131,Active,2022-09-26 00:00:00
124525,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26 00:00:00,9621,Savings,184,Active,2023-01-13 00:00:00
124526,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17 00:00:00,4056,Savings,239,Active,2022-05-13 00:00:00

In [86]:
# Count each account type

account_counts = cus_acc['account_type'].value_counts()

print(account_counts)
print("The most popular:")
print(account_counts.head(1))

account_type
Savings     51994
Cheque      49456
Credit      12409
Business    10010
Nan           658
Name: count, dtype: int64
The most popular:
account_type
Savings    51994
Name: count, dtype: int64

# Customer Analytics

In [87]:
import pandas as pd 
customers = pd.read_csv("data/processed/cleanedCustomers.csv")
customers = customers.drop(columns=['Unnamed: 0'])
customers

,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24 00:00:00
1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25 00:00:00
2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18 00:00:00
3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21 00:00:00
4,5,Emma,Molefe,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02 00:00:00
...,...,...,...,...,...,...,...,...,...
100085,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03 00:00:00
100086,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,Nan,2016-12-26 00:00:00
100087,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28 00:00:00
100088,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19 00:00:00
100089,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17 00:00:00

In [88]:
#Count customers that the bank has
print("The Number of customers the bank has is:",customers['customer_id'].count())

The Number of customers the bank has is: 100090

In [89]:
# Which province has the most customers
leading_province = customers['province'].value_counts()

print(leading_province) 
print("The province with most customers is:")
print( leading_province.head(1))

province
Gauteng          29859
Kwazulu-Natal    20090
Western Cape     11959
Eastern Cape     10115
Limpopo           7942
Free State        6044
Mpumalanga        5991
North West        5084
Northern Cape     3006
Name: count, dtype: int64
The province with most customers is:
province
Gauteng    29859
Name: count, dtype: int64

# Cleaning transactions

In [90]:
import pandas as pd
transactions = pd.read_csv("data/raw/transactions.csv")
transactions.info()
transactions

<class 'pandas.DataFrame'>
RangeIndex: 1003000 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1003000 non-null  int64
 1   account_id        1003000 non-null  str
 2   merchant_id       973296 non-null   str
 3   transaction_date  1003000 non-null  str
 4   transaction_type  1003000 non-null  str
 5   channel           991088 non-null   str
 6   amount            991013 non-null   str
 7   currency          1003000 non-null  str
 8   description       1003000 non-null  str
dtypes: int64(1), str(8)
memory usage: 68.9 MB

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
0,1,65820,19009.0,2025-05-26,Deposit,pos,448.44,ZAR,Transfer
1,2,9167,15505.0,2026-05-06,Purchase,atm,85.0,ZAR,Online purchase
2,3,86080,12053.0,2025-12-24,Payment,ATM,459.94,ZAR,Retail purchase
3,4,56039,10816.0,2025-10-05,Transfer,mobile,511.36,ZAR,Bill payment
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,POS,189.0,ZAR,Online purchase
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,ZAR,Salary

In [91]:
# Convert data type: Date from string to datetime
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date'],
    format= 'mixed',
    dayfirst= True,
    errors= 'coerce'
)
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1003000 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1003000 non-null  int64
 1   account_id        1003000 non-null  str
 2   merchant_id       973296 non-null   str
 3   transaction_date  999991 non-null   datetime64[us]
 4   transaction_type  1003000 non-null  str
 5   channel           991088 non-null   str
 6   amount            991013 non-null   str
 7   currency          1003000 non-null  str
 8   description       1003000 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 68.9 MB

In [92]:
transactions[transactions['transaction_date'].isna()]

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
7,8,10993,4415.0,NaT,Purchase,ATM,7761.33,ZAR,Retail purchase
202,203,52411,5862.0,NaT,Withdrawal,Online,729.49,ZAR,Online purchase
233,234,99651,14179.0,NaT,Purchase,Online,0.0,ZAR,Retail purchase
257,258,117131,18874.0,NaT,Deposit,POS,377.94,ZAR,Retail purchase
1059,1060,117131,9438.0,NaT,Transfer,Mobile,2080.34,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1001559,310564,104531,7536.0,NaT,Purchase,Online,3677.54,ZAR,Salary
1002222,475633,81320,9287.0,NaT,Purchase,Online,2384.19,ZAR,Transfer
1002406,603683,33447,478.0,NaT,Withdrawal,ATM,1006.4,ZAR,Retail purchase
1002635,543745,83999,345.0,NaT,Deposit,Online,15973.84,ZAR,Cash withdrawal
1002980,703981,19032,15279.0,NaT,Purchase,Mobile,1435.68,ZAR,Cash withdrawal

In [93]:
# Display Duplicates in dataset 
transactions[transactions.duplicated()]
transactions[transactions.duplicated() == True]

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
1000000,412535,36917,NaN,2026-02-22,Withdrawal,ATM,0.0,ZAR,Salary
1000001,515920,96209,4944.0,2025-06-11,Purchase,Mobile,148.85,ZAR,Online purchase
1000002,879751,90551,15006.0,2025-11-01,Purchase,Mobile,225.77,ZAR,Bill payment
1000004,109959,17762,15066.0,2026-01-07,Payment,ATM,486.35,USD,Online purchase
1000008,607097,85753,6048.0,2026-09-02,Deposit,App,167.61,ZAR,Online purchase
...,...,...,...,...,...,...,...,...,...
1002993,93399,81661,10311.0,2025-10-01,Purchase,Online,89.52,ZAR,Bill payment
1002994,228396,100338,16106.0,2025-11-08,Deposit,Mobile,298.07,ZAR,Online purchase
1002995,760111,16022,3336.0,2026-04-06,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment

In [94]:
# Delete Duplicates:
transactions = transactions.drop_duplicates()

transactions[transactions.duplicated() == True]

Empty DataFrame
Columns: [transaction_id, account_id, merchant_id, transaction_date, transaction_type, channel, amount, currency, description]
Index: []

In [95]:


import numpy as np


transactions = transactions.replace(np.nan, "NaN")
transactions['transaction_date'].replace(pd.NaT, 0)

transactions.info()

<class 'pandas.DataFrame'>
Index: 1001065 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1001065 non-null  int64
 1   account_id        1001065 non-null  str
 2   merchant_id       1001065 non-null  str
 3   transaction_date  998056 non-null   datetime64[us]
 4   transaction_type  1001065 non-null  str
 5   channel           1001065 non-null  str
 6   amount            1001065 non-null  str
 7   currency          1001065 non-null  str
 8   description       1001065 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 76.4 MB

In [96]:
import pandas as pd
transactions = pd.read_csv("data/processed/transactions_clean.csv")

In [97]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1001065 entries, 0 to 1001064
Data columns (total 10 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1001065 non-null  int64
 1   transaction_id    1001065 non-null  int64
 2   account_id        1001065 non-null  str
 3   merchant_id       971403 non-null   str
 4   transaction_date  998056 non-null   str
 5   transaction_type  1001065 non-null  str
 6   channel           1001065 non-null  str
 7   amount            989078 non-null   float64
 8   currency          1001065 non-null  str
 9   description       1001065 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 76.4 MB

# Merging datasets Customers, Accounts and Transactions

In [178]:
import pandas as pd
accounts = pd.read_csv("data/processed/cleanedAccounts2.csv", parse_dates=['opened_date'])
transactions = pd.read_csv("data/processed/transactions_clean_final.csv", parse_dates=['transaction_date'])
customers = pd.read_csv("data/processed/cleanedCustomers2.csv", parse_dates=['customer_since'])

In [164]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 124401 entries, 0 to 124400
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      124401 non-null  int64
 1   account_id      124401 non-null  int64
 2   customer_id     124401 non-null  int64
 3   account_type    124401 non-null  str
 4   branch_id       124401 non-null  int64
 5   account_status  124401 non-null  str
 6   opened_date     124401 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(4), str(2)
memory usage: 6.6 MB

In [165]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1001065 entries, 0 to 1001064
Data columns (total 11 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   Unnamed: 0           1001065 non-null  int64
 1   transaction_id       1001065 non-null  int64
 2   account_id           1001065 non-null  str
 3   merchant_id          971403 non-null   str
 4   transaction_date     1001065 non-null  datetime64[us]
 5   transaction_type     1001065 non-null  str
 6   channel              1001065 non-null  str
 7   amount               1001065 non-null  float64
 8   currency             1001065 non-null  str
 9   description          1001065 non-null  str
 10  is_high_transaction  1001065 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(2), str(6)
memory usage: 77.3 MB

In [166]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100090 entries, 0 to 100089
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         100090 non-null  int64
 1   customer_id        100090 non-null  int64
 2   first_name         100090 non-null  str
 3   last_name          100090 non-null  str
 4   age                100090 non-null  int64
 5   province           100090 non-null  str
 6   city               100090 non-null  str
 7   employment_status  100090 non-null  str
 8   income             100090 non-null  float64
 9   customer_since     100090 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(3), str(5)
memory usage: 7.6 MB

In [179]:
accounts.account_id = accounts.account_id.astype(str)

In [181]:
trans_acc = pd.merge(accounts,transactions, how='inner', on="account_id")
trans_acc.info()

<class 'pandas.DataFrame'>
RangeIndex: 994216 entries, 0 to 994215
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0_x         994216 non-null  int64
 1   account_id           994216 non-null  str
 2   customer_id          994216 non-null  int64
 3   account_type         994216 non-null  str
 4   branch_id            994216 non-null  int64
 5   account_status       994216 non-null  str
 6   opened_date          994216 non-null  datetime64[us]
 7   Unnamed: 0_y         994216 non-null  int64
 8   transaction_id       994216 non-null  int64
 9   merchant_id          964779 non-null  str
 10  transaction_date     994216 non-null  datetime64[us]
 11  transaction_type     994216 non-null  str
 12  channel              994216 non-null  str
 13  amount               994216 non-null  float64
 14  currency             994216 non-null  str
 15  description          994216 non-null  str
 16  is_high_transaction  994216 non-null  bool
dtypes: bool(1), datetime64[us](2), float64(1), int64(5), str(8)
memory usage: 122.3 MB