# Exchange Rates

In [7]:
import pandas as pd
exchange_rates = pd.read_csv("exchange_rates.csv")
exchange_rates.info()
exchange_rates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578 entries, 0 to 577
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     578 non-null    object
 1   ZAR_USD  578 non-null    float64
 2   ZAR_EUR  578 non-null    float64
dtypes: float64(2), object(1)
memory usage: 13.7+ KB

             date  ZAR_USD  ZAR_EUR
0      2025-01-01  17.6151  18.1683
1      2025-01-02  17.5550  19.4497
2      2025-01-03  17.4970  18.9149
3     2025-01-04   17.8794  18.6521
4      2025-01-05  17.8951  19.8447
..            ...      ...      ...
573    2026-07-28  17.5889  18.7176
574    2026-07-29  18.1792  20.3421
575    2026-07-30  17.8557  18.8886
576    2026-01-01  18.9530  19.3441
577    2026-08-01  18.4326  19.2865

[578 rows x 3 columns]

In [8]:
# Convert data type: Date from string to datetime
exchange_rates['date'] = pd.to_datetime(
    exchange_rates['date'],
    format= 'mixed',
    dayfirst= True,
    errors= 'coerce'
)
exchange_rates

          date  ZAR_USD  ZAR_EUR
0   2025-01-01  17.6151  18.1683
1   2025-01-02  17.5550  19.4497
2   2025-01-03  17.4970  18.9149
3   2025-04-01  17.8794  18.6521
4   2025-01-05  17.8951  19.8447
..         ...      ...      ...
573 2026-07-28  17.5889  18.7176
574 2026-07-29  18.1792  20.3421
575 2026-07-30  17.8557  18.8886
576 2026-01-01  18.9530  19.3441
577 2026-08-01  18.4326  19.2865

[578 rows x 3 columns]

In [9]:
# Display Duplicates in dataset
exchange_rates[exchange_rates.duplicated() == True]

Empty DataFrame
Columns: [date, ZAR_USD, ZAR_EUR]
Index: []

# Transactions

In [2]:
import pandas as pd
transactions = pd.read_csv("transactions.csv")
transactions.info()
transactions

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003000 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1003000 non-null  int64
 1   account_id        1003000 non-null  object
 2   merchant_id       973296 non-null   object
 3   transaction_date  1003000 non-null  object
 4   transaction_type  1003000 non-null  object
 5   channel           991088 non-null   object
 6   amount            991013 non-null   object
 7   currency          1003000 non-null  object
 8   description       1003000 non-null  object
dtypes: int64(1), object(8)
memory usage: 68.9+ MB

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
0,1,65820,19009.0,2025-05-26,Deposit,pos,448.44,ZAR,Transfer
1,2,9167,15505.0,2026-05-06,Purchase,atm,85.0,ZAR,Online purchase
2,3,86080,12053.0,2025-12-24,Payment,ATM,459.94,ZAR,Retail purchase
3,4,56039,10816.0,2025-10-05,Transfer,mobile,511.36,ZAR,Bill payment
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,POS,189.0,ZAR,Online purchase
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,ZAR,Salary

In [3]:
# Convert data type: Date from string to datetime
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date'],
    format= 'mixed',
    dayfirst= True,
    errors= 'coerce'
)
transactions

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
0,1,65820,19009.0,2025-05-26,Deposit,pos,448.44,ZAR,Transfer
1,2,9167,15505.0,2026-05-06,Purchase,atm,85.0,ZAR,Online purchase
2,3,86080,12053.0,2025-12-24,Payment,ATM,459.94,ZAR,Retail purchase
3,4,56039,10816.0,2025-10-05,Transfer,mobile,511.36,ZAR,Bill payment
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,POS,189.0,ZAR,Online purchase
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,ZAR,Salary

In [15]:
# Display Duplicates in dataset
transactions[transactions.duplicated()]
transactions[transactions.duplicated() == True]

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
1000000,412535,36917,NaN,2026-02-22,Withdrawal,ATM,0.0,ZAR,Salary
1000001,515920,96209,4944.0,2025-06-11,Purchase,Mobile,148.85,ZAR,Online purchase
1000002,879751,90551,15006.0,2025-11-01,Purchase,Mobile,225.77,ZAR,Bill payment
1000004,109959,17762,15066.0,2026-07-01,Payment,ATM,486.35,USD,Online purchase
1000008,607097,85753,6048.0,2026-02-09,Deposit,App,167.61,ZAR,Online purchase
...,...,...,...,...,...,...,...,...,...
1002993,93399,81661,10311.0,2025-01-10,Purchase,Online,89.52,ZAR,Bill payment
1002994,228396,100338,16106.0,2025-08-11,Deposit,Mobile,298.07,ZAR,Online purchase
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment

In [19]:
# Delete Duplicates:
transactions = transactions.drop_duplicates()

transactions[transactions.duplicated() == True]

Empty DataFrame
Columns: [transaction_id, account_id, merchant_id, transaction_date, transaction_type, channel, amount, currency, description]
Index: []