# Exchange Rates

In [326]:
import pandas as pd
exchange_rates = pd.read_csv("data/raw/exchange_rates.csv")
exchange_rates.info()
exchange_rates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578 entries, 0 to 577
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     578 non-null    object
 1   ZAR_USD  578 non-null    float64
 2   ZAR_EUR  578 non-null    float64
dtypes: float64(2), object(1)
memory usage: 13.7+ KB

             date  ZAR_USD  ZAR_EUR
0      2025-01-01  17.6151  18.1683
1      2025-01-02  17.5550  19.4497
2      2025-01-03  17.4970  18.9149
3     2025-01-04   17.8794  18.6521
4      2025-01-05  17.8951  19.8447
..            ...      ...      ...
573    2026-07-28  17.5889  18.7176
574    2026-07-29  18.1792  20.3421
575    2026-07-30  17.8557  18.8886
576    2026-01-01  18.9530  19.3441
577    2026-08-01  18.4326  19.2865

[578 rows x 3 columns]

In [327]:
# Convert data type: Date from string to datetime
exchange_rates['date'] = pd.to_datetime(
    exchange_rates['date'],
    format= 'mixed',
    dayfirst= True,
    errors= 'coerce'
)
exchange_rates

          date  ZAR_USD  ZAR_EUR
0   2025-01-01  17.6151  18.1683
1   2025-01-02  17.5550  19.4497
2   2025-01-03  17.4970  18.9149
3   2025-04-01  17.8794  18.6521
4   2025-01-05  17.8951  19.8447
..         ...      ...      ...
573 2026-07-28  17.5889  18.7176
574 2026-07-29  18.1792  20.3421
575 2026-07-30  17.8557  18.8886
576 2026-01-01  18.9530  19.3441
577 2026-08-01  18.4326  19.2865

[578 rows x 3 columns]

In [328]:
# Display Duplicates in dataset
exchange_rates[exchange_rates.duplicated() == True]

Empty DataFrame
Columns: [date, ZAR_USD, ZAR_EUR]
Index: []

In [329]:
exchange_rates.to_csv("data/processed/exchange_rates_clean.csv")

# Transactions

In [330]:
import pandas as pd
transactions = pd.read_csv("data/raw/transactions.csv")
transactions.info()
transactions

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003000 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1003000 non-null  int64
 1   account_id        1003000 non-null  object
 2   merchant_id       973296 non-null   object
 3   transaction_date  1003000 non-null  object
 4   transaction_type  1003000 non-null  object
 5   channel           991088 non-null   object
 6   amount            991013 non-null   object
 7   currency          1003000 non-null  object
 8   description       1003000 non-null  object
dtypes: int64(1), object(8)
memory usage: 68.9+ MB

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
0,1,65820,19009.0,2025-05-26,Deposit,pos,448.44,ZAR,Transfer
1,2,9167,15505.0,2026-05-06,Purchase,atm,85.0,ZAR,Online purchase
2,3,86080,12053.0,2025-12-24,Payment,ATM,459.94,ZAR,Retail purchase
3,4,56039,10816.0,2025-10-05,Transfer,mobile,511.36,ZAR,Bill payment
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,POS,189.0,ZAR,Online purchase
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,ZAR,Salary

In [331]:
# Convert data type: Date from string to datetime
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date'],
    format= 'mixed',
    dayfirst= True,
    errors= 'coerce'
)
transactions

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
0,1,65820,19009.0,2025-05-26,Deposit,pos,448.44,ZAR,Transfer
1,2,9167,15505.0,2026-05-06,Purchase,atm,85.0,ZAR,Online purchase
2,3,86080,12053.0,2025-12-24,Payment,ATM,459.94,ZAR,Retail purchase
3,4,56039,10816.0,2025-10-05,Transfer,mobile,511.36,ZAR,Bill payment
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,ZAR,Bill payment
...,...,...,...,...,...,...,...,...,...
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,POS,189.0,ZAR,Online purchase
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,ZAR,Salary

In [332]:
# Display Duplicates in dataset
transactions[transactions.duplicated()]
transactions[transactions.duplicated() == True]

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
1000000,412535,36917,NaN,2026-02-22,Withdrawal,ATM,0.0,ZAR,Salary
1000001,515920,96209,4944.0,2025-06-11,Purchase,Mobile,148.85,ZAR,Online purchase
1000002,879751,90551,15006.0,2025-11-01,Purchase,Mobile,225.77,ZAR,Bill payment
1000004,109959,17762,15066.0,2026-07-01,Payment,ATM,486.35,USD,Online purchase
1000008,607097,85753,6048.0,2026-02-09,Deposit,App,167.61,ZAR,Online purchase
...,...,...,...,...,...,...,...,...,...
1002993,93399,81661,10311.0,2025-01-10,Purchase,Online,89.52,ZAR,Bill payment
1002994,228396,100338,16106.0,2025-08-11,Deposit,Mobile,298.07,ZAR,Online purchase
1002995,760111,16022,3336.0,2026-06-04,Deposit,Online,920.44,ZAR,Transfer
1002996,989369,109728,9164.0,2026-05-19,Purchase,Online,935.24,ZAR,Salary
1002998,698682,111100,12297.0,2025-04-21,Purchase,Online,1062.72,ZAR,Bill payment

In [333]:
# Delete Duplicates:
transactions = transactions.drop_duplicates()

transactions[transactions.duplicated() == True]

Empty DataFrame
Columns: [transaction_id, account_id, merchant_id, transaction_date, transaction_type, channel, amount, currency, description]
Index: []

In [334]:
transactions[transactions['merchant_id'].isna()]

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description
82,83,27522,NaN,2026-05-19,Purchase,Online,1347.96,USD,Retail purchase
140,141,96714,NaN,2025-11-22,Transfer,Atm,1217.32,ZAR,Bill payment
161,162,88880,NaN,2025-12-20,Payment,Online,838.94,ZAR,Online purchase
167,168,59455,NaN,2026-01-09,PAYMENT,Online,0.0,USD,Salary
186,187,5634,NaN,2025-04-25,Purchase,pos,379.82,ZAR,Retail purchase
...,...,...,...,...,...,...,...,...,...
1002790,286913,12573,NaN,2026-02-13,Refund,Online,312.94,ZAR,Retail purchase
1002879,515451,111691,NaN,2025-10-26,Purchase,Mobile,0.0,ZAR,Transfer
1002944,457987,44366,NaN,2026-03-10,Transfer,Branch,1318.4,ZAR,Transfer
1002950,299583,52532,NaN,2025-10-04,Purchase,Mobile,266.47,EUR,Salary
1002989,321736,13591,NaN,2026-07-24,Purchase,Mobile,1438.58,ZAR,Online purchase

In [365]:
transactions.merchant_id.fillna("Unknown")
transactions.info()

AttributeError: 'Series' object has no attribute 'merchant_id'

In [336]:
import numpy as np
transactions = transactions.replace(np.nan, "NaN")

In [337]:
import numpy as np
transaction_date  = transactions.replace(np.nan, "NaN")

In [338]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1001065 entries, 0 to 1002999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1001065 non-null  int64
 1   account_id        1001065 non-null  object
 2   merchant_id       1001065 non-null  object
 3   transaction_date  998056 non-null   datetime64[ns]
 4   transaction_type  1001065 non-null  object
 5   channel           1001065 non-null  object
 6   amount            1001065 non-null  object
 7   currency          1001065 non-null  object
 8   description       1001065 non-null  object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 76.4+ MB

In [339]:
#Clean Transaction Type Categories:

transactions.transaction_type = pd.Series(transactions.transaction_type).str.strip().str.title()

transactions.transaction_type.unique()

array(['Deposit', 'Purchase', 'Payment', 'Transfer', 'Withdrawal',
       'Refund'], dtype=object)

In [340]:
#Clean Channel Categories:
transactions.channel = pd.Series(transactions.channel).str.strip().str.title()

transactions.channel.unique()

array(['Pos', 'Atm', 'Mobile', 'Online', 'Branch', 'App', 'Nan'],
      dtype=object)

In [341]:
#Clean Currency Categories:
transactions.currency = transactions.currency.str.strip().str.upper()
transactions.currency = transactions.currency.str.replace('ZAR', "R")


transactions.currency.unique()

array(['R', 'USD', 'EUR'], dtype=object)

In [342]:
# transactions[transactions['transaction_date'].isnull() == True]
transactions['transaction_date'] = transactions['transaction_date'].fillna(pd.Timestamp('1900-01-01'))
# transactions

In [343]:
transactions.amount =transactions.amount.str.replace("R","")
transactions.amount =transactions.amount.str.replace(" ","")
transactions.amount =transactions.amount.str.replace(",","")

In [344]:
transactions.amount = transactions.amount.astype(float)

import numpy as np
transactions['amount'] = transactions['amount'].fillna(np.float64('0.0')) # Replace missing value with '0.0'

In [345]:
transactions.to_csv("data/processed/transactions_clean.csv")

# Transaction Feature Engineering

In [ ]:
# Add a boolean feature: True if amount > 24999

import numpy as np

# Define thresholds where EUR & USD = R24999
thresholds = {
    "ZAR": 24999,
    "EUR": 1330,
    "USD": 1516
}


transactions["is_high_transaction"] = np.where(
    (transactions["currency"] == "ZAR") & (transactions["amount"] > thresholds["ZAR"]), True,
    np.where(
        (transactions["currency"] == "EUR") & (transactions["amount"] > thresholds["EUR"]), True,
        np.where(
            (transactions["currency"] == "USD") & (transactions["amount"] > thresholds["USD"]), True,
            False
        )
    )
)



transactions

,transaction_id,account_id,merchant_id,transaction_date,transaction_type,channel,amount,currency,description,is_high_transaction
0,1,65820,19009.0,2025-05-26,Deposit,Pos,448.44,R,Transfer,False
1,2,9167,15505.0,2026-05-06,Purchase,Atm,85.00,R,Online purchase,False
2,3,86080,12053.0,2025-12-24,Payment,Atm,459.94,R,Retail purchase,False
3,4,56039,10816.0,2025-10-05,Transfer,Mobile,511.36,R,Bill payment,False
4,5,69271,9603.0,2025-01-27,Deposit,Mobile,362.61,R,Bill payment,False
...,...,...,...,...,...,...,...,...,...,...
1002984,554267,41324,17708.0,2025-05-08,Payment,Pos,156.88,R,Transfer,False
1002989,321736,13591,NaN,2026-07-24,Purchase,Mobile,1438.58,R,Online purchase,False
1002990,341329,58456,14524.0,2025-02-05,Deposit,Atm,1017.77,R,Bill payment,False
1002997,210561,42406,4358.0,2025-10-31,Withdrawal,Pos,189.00,R,Online purchase,False
1002999,46641,82526,3556.0,2025-08-28,Transfer,Pos,3318.48,R,Salary,False

In [362]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1001065 entries, 0 to 1002999
Data columns (total 10 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   transaction_id       1001065 non-null  int64
 1   account_id           1001065 non-null  object
 2   merchant_id          1001065 non-null  object
 3   transaction_date     1001065 non-null  datetime64[ns]
 4   transaction_type     1001065 non-null  object
 5   channel              1001065 non-null  object
 6   amount               1001065 non-null  float64
 7   currency             1001065 non-null  object
 8   description          1001065 non-null  object
 9   is_high_transaction  1001065 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 77.3+ MB