# cleaning data fraud labels

In [5]:
import pandas as pd

fraud_labels = pd.read_csv("fraud_labels.csv")
fraud_labels.info()
fraud_labels

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1000000 non-null  int64
 1   is_fraud        1000000 non-null  int64
 2   fraud_reason    24260 non-null    object
dtypes: int64(2), object(1)
memory usage: 22.9+ MB

        transaction_id  is_fraud fraud_reason
0                    1         0          NaN
1                    2         0          NaN
2                    3         0          NaN
3                    4         0          NaN
4                    5         0          NaN
...                ...       ...          ...
999995          999996         0          NaN
999996          999997         0          NaN
999997          999998         0          NaN
999998          999999         0          NaN
999999         1000000         0          NaN

[1000000 rows x 3 columns]

In [ ]:
fraud_labels.info()

fraud_labels.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 999001 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   transaction_id  999001 non-null  float64
 1   is_fraud        999001 non-null  float64
 2   fraud_reason    999001 non-null  object
dtypes: float64(2), object(1)
memory usage: 30.5+ MB

        transaction_id       is_fraud fraud_reason
count    999001.000000  999001.000000       999001
unique             NaN            NaN           35
top                NaN            NaN     No Fraud
freq               NaN            NaN       974737
mean     499994.599537       0.006387          NaN
std      288673.182475       0.079665          NaN
min           1.000000       0.000000          NaN
25%      249996.000000       0.000000          NaN
50%      500005.000000       0.000000          NaN
75%      749987.000000       0.000000          NaN
max     1000000.000000       1.000000          NaN

In [10]:
# Check fraud distribution
fraud_labels['is_fraud'].value_counts()

is_fraud
0    993611
1      6389
Name: count, dtype: int64

In [19]:
# Missing values
fraud_labels.isnull().sum()

transaction_id         0
is_fraud               0
fraud_reason      975740
dtype: int64

In [18]:
# Non-fraud transactions with a fraud reason
invalid_1 = fraud_labels[(fraud_labels['is_fraud'] == 0) & (fraud_labels['fraud_reason'].notna())]

# Fraud transactions without a fraud reason
invalid_2 = fraud_labels[(fraud_labels['is_fraud'] == 1) & (fraud_labels['fraud_reason'].isna())]

print(len(invalid_1))
print(len(invalid_2))

17902
31

In [ ]:
#handling missing values
fraud_labels.loc[
(fraud_labels['is_fraud'] == 1) & (fraud_labels['fraud_reason'].isna()),
'fraud_reason'
] = 'Unknown'

In [ ]:
#keep NaN or replace with a label
fraud_labels['fraud_reason'] = fraud_labels['fraud_reason'].fillna('No Fraud')

In [ ]:
# removing duplicates
fraud_labels = fraud_labels.drop_duplicates()

fraud_labels[fraud_labels.duplicated() == True]

Empty DataFrame
Columns: [transaction_id, is_fraud, fraud_reason]
Index: []

In [55]:
# ensuring ID's unique
fraud_labels['transaction_id'].nunique()

fraud_labels.shape[0]

999001

In [ ]:
# finding duplicates
"fraud_labels.duplicated()"

'fraud_labels.duplicated()'

In [59]:
# correcting data types
fraud_labels['transaction_id'] = fraud_labels['transaction_id'].astype(float)
fraud_labels['is_fraud'] = fraud_labels['is_fraud'].astype(float)
fraud_labels.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999001 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   transaction_id  999001 non-null  float64
 1   is_fraud        999001 non-null  float64
 2   fraud_reason    999001 non-null  object
dtypes: float64(2), object(1)
memory usage: 30.5+ MB

In [60]:
# standardazing
fraud_labels['fraud_reason'] = (
fraud_labels['fraud_reason']
.str.strip()
.str.lower()
)
fraud_labels

        transaction_id  is_fraud fraud_reason
0                  1.0       0.0     no fraud
1                  2.0       0.0     no fraud
2                  3.0       0.0     no fraud
3                  4.0       0.0     no fraud
4                  5.0       0.0     no fraud
...                ...       ...          ...
999995        999996.0       0.0     no fraud
999996        999997.0       0.0     no fraud
999997        999998.0       0.0     no fraud
999998        999999.0       0.0     no fraud
999999       1000000.0       0.0     no fraud

[999001 rows x 3 columns]

In [ ]:
# Validation
print(fraud_labels.isnull().sum())
print(fraud_labels['is_fraud'].value_counts())

# Check for invalid combinations again
fraud_labels[
((fraud_labels['is_fraud'] == 0) & (fraud_labels['fraud_reason'] != 'No Fraud'))
]

transaction_id    0
is_fraud          0
fraud_reason      0
dtype: int64
is_fraud
0.0    992620
1.0      6381
Name: count, dtype: int64

        transaction_id  is_fraud fraud_reason
0                  1.0       0.0     no fraud
1                  2.0       0.0     no fraud
2                  3.0       0.0     no fraud
3                  4.0       0.0     no fraud
4                  5.0       0.0     no fraud
...                ...       ...          ...
999995        999996.0       0.0     no fraud
999996        999997.0       0.0     no fraud
999997        999998.0       0.0     no fraud
999998        999999.0       0.0     no fraud
999999       1000000.0       0.0     no fraud

[992620 rows x 3 columns]