# Cleaning Fraud Labels Data

In [475]:
import pandas as pd

fraud_labels = pd.read_csv("data/raw/fraud_labels.csv")
fraud_labels

        transaction_id  is_fraud fraud_reason
0                    1         0          NaN
1                    2         0          NaN
2                    3         0          NaN
3                    4         0          NaN
4                    5         0          NaN
...                ...       ...          ...
999995          999996         0          NaN
999996          999997         0          NaN
999997          999998         0          NaN
999998          999999         0          NaN
999999         1000000         0          NaN

[1000000 rows x 3 columns]

In [476]:
fraud_labels.info()

fraud_labels.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1000000 non-null  int64
 1   is_fraud        1000000 non-null  int64
 2   fraud_reason    24260 non-null    object
dtypes: int64(2), object(1)
memory usage: 22.9+ MB

        transaction_id        is_fraud fraud_reason
count   1000000.000000  1000000.000000        24260
unique             NaN             NaN           33
top                NaN             NaN         nan
freq               NaN             NaN         6034
mean     499999.788612        0.006389          NaN
std      288677.403098        0.079676          NaN
min           1.000000        0.000000          NaN
25%      249990.750000        0.000000          NaN
50%      500018.500000        0.000000          NaN
75%      750002.250000        0.000000          NaN
max     1000000.000000        1.000000          NaN

In [477]:
# Check fraud distribution
fraud_labels['is_fraud'].value_counts()

is_fraud
0    993611
1      6389
Name: count, dtype: int64

In [478]:
# Missing values
fraud_labels.isnull().sum()

transaction_id         0
is_fraud               0
fraud_reason      975740
dtype: int64

In [479]:
# Non-fraud transactions with a fraud reason
invalid_1 = fraud_labels[(fraud_labels['is_fraud'] == 0) & (fraud_labels['fraud_reason'].notna())]

# Fraud transactions without a fraud reason
invalid_2 = fraud_labels[(fraud_labels['is_fraud'] == 1) & (fraud_labels['fraud_reason'].isna())]

print(len(invalid_1))
print(len(invalid_2))

17902
31

In [480]:
#handling missing values
fraud_labels.loc[
(fraud_labels['is_fraud'] == 1) & (fraud_labels['fraud_reason'].isna()),
'fraud_reason'
] = 'Unknown'

In [481]:
#keep NaN or replace with a label
fraud_labels['fraud_reason'] = fraud_labels['fraud_reason'].fillna('No Fraud')

In [482]:
# removing duplicates
fraud_labels = fraud_labels.drop_duplicates()

fraud_labels[fraud_labels.duplicated() == True]

Empty DataFrame
Columns: [transaction_id, is_fraud, fraud_reason]
Index: []

In [483]:
# ensuring ID's unique
fraud_labels['transaction_id'].nunique()

fraud_labels.shape[0]

999059

In [484]:
# finding duplicates
"fraud_labels.duplicated()"

'fraud_labels.duplicated()'

In [485]:
# correcting data types
fraud_labels['transaction_id'] = fraud_labels['transaction_id'].astype(float)
fraud_labels['is_fraud'] = fraud_labels['is_fraud'].astype(float)
fraud_labels.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999059 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   transaction_id  999059 non-null  float64
 1   is_fraud        999059 non-null  float64
 2   fraud_reason    999059 non-null  object
dtypes: float64(2), object(1)
memory usage: 30.5+ MB

C:\Users\E1023397\AppData\Local\Temp\ipykernel_32900\3959015426.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraud_labels['transaction_id'] = fraud_labels['transaction_id'].astype(float)
C:\Users\E1023397\AppData\Local\Temp\ipykernel_32900\3959015426.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraud_labels['is_fraud'] = fraud_labels['is_fraud'].astype(float)

In [486]:
# standardazing
fraud_labels['fraud_reason'] = (
fraud_labels['fraud_reason']
.str.strip()
.str.lower()
)
fraud_labels

C:\Users\E1023397\AppData\Local\Temp\ipykernel_32900\3426566504.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraud_labels['fraud_reason'] = (

        transaction_id  is_fraud fraud_reason
0                  1.0       0.0     no fraud
1                  2.0       0.0     no fraud
2                  3.0       0.0     no fraud
3                  4.0       0.0     no fraud
4                  5.0       0.0     no fraud
...                ...       ...          ...
999995        999996.0       0.0     no fraud
999996        999997.0       0.0     no fraud
999997        999998.0       0.0     no fraud
999998        999999.0       0.0     no fraud
999999       1000000.0       0.0     no fraud

[999059 rows x 3 columns]

In [487]:
# Validation
print(fraud_labels.isnull().sum())
print(fraud_labels['is_fraud'].value_counts())

# Check for invalid combinations again
fraud_labels[
((fraud_labels['is_fraud'] == 0) & (fraud_labels['fraud_reason'] != 'No Fraud'))
]

transaction_id    0
is_fraud          0
fraud_reason      0
dtype: int64
is_fraud
0.0    992670
1.0      6389
Name: count, dtype: int64

        transaction_id  is_fraud fraud_reason
0                  1.0       0.0     no fraud
1                  2.0       0.0     no fraud
2                  3.0       0.0     no fraud
3                  4.0       0.0     no fraud
4                  5.0       0.0     no fraud
...                ...       ...          ...
999995        999996.0       0.0     no fraud
999996        999997.0       0.0     no fraud
999997        999998.0       0.0     no fraud
999998        999999.0       0.0     no fraud
999999       1000000.0       0.0     no fraud

[992670 rows x 3 columns]

In [488]:
fraud_labels.to_csv("data/processed/fraud_label_cleaned.csv")

# Cleaning Merchants Data

In [489]:
import pandas as pd

merchants = pd.read_csv("data/raw/merchants.csv")
merchants.info()
merchants

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   merchant_id        20000 non-null  int64
 1   merchant_name      20000 non-null  object
 2   merchant_category  19881 non-null  object
 3   province           20000 non-null  object
 4   city               19878 non-null  object
 5   risk_rating        19869 non-null  object
dtypes: int64(1), object(5)
memory usage: 937.6+ KB

,merchant_id,merchant_name,merchant_category,province,city,risk_rating
0,1,merchant 00001,Online Services,Free State,Bethlehem,Low
1,2,Merchant 00002,Grocery,Mpumalanga,Secunda,Low
2,3,Merchant 00003,Clothing,Limpopo,Polokwane,Medium
3,4,Merchant 00004,Grocery,Mpumalanga,Mbombela,Low
4,5,Merchant 00005,Travel,Free State,Bloemfontein,Medium
...,...,...,...,...,...,...
19995,19996,Merchant 19996,Online Services,Mpumalanga,Mbombela,Low
19996,19997,Merchant 19997,Restaurant,KwaZulu-Natal,Durban,Low
19997,19998,Merchant 19998,Grocery,KwaZulu-Natal,Richards Bay,Low
19998,19999,Merchant 19999,Grocery,Free State,Welkom,Low
19999,20000,Merchant 20000,Online Services,Mpumalanga,Mbombela,High

In [490]:
# #This helps identify spelling inconsistencies.

merchants.city = merchants.city.str.strip()
# # merchants the white and space bar space
merchants['city'] = merchants['city'].str.replace(r'\s+', ' ', regex= True)
merchants.city = merchants.city.str.title()

# merchants.city.unique()

merchants.city.unique()

array(['Bethlehem', 'Secunda', 'Polokwane', 'Mbombela', 'Bloemfontein',
       'Pietermaritzburg', 'Johannesburg', 'Gqeberha', 'Klerksdorp',
       'Stellenbosch', 'Welkom', 'Rustenburg', 'Mahikeng', 'Thohoyandou',
       'Emalahleni', 'Durban', 'Midrand', 'Richards Bay', 'East London',
       'Pretoria', 'Upington', 'Mthatha', 'George', 'Paarl', 'Soweto',
       'Kimberley', 'Tzaneen', nan, 'Kuruman', 'Cape Town'], dtype=object)

In [491]:
merchants.province= merchants.province.str.strip()
# # merchants the white and space bar space
merchants['province'] = merchants['province'].str.replace("  ", " ")
merchants.province = merchants.province.str.title()


# #Expected provinces
merchants.province.unique()

array(['Free State', 'Mpumalanga', 'Limpopo', 'Kwazulu-Natal', 'Gauteng',
       'Eastern Cape', 'North West', 'Western Cape', 'Northern Cape'],
      dtype=object)

In [492]:
merchants.merchant_category= merchants.merchant_category.str.strip()
# # merchants the white and space bar space
merchants['merchant_category'] = merchants['merchant_category'].str.replace("  ", " ")
merchants.merchant_category = merchants.merchant_category.str.title()
merchants.merchant_category.unique()

array(['Online Services', 'Grocery', 'Clothing', 'Travel',
       'Entertainment', 'Fuel', 'Healthcare', 'Electronics', 'Other',
       'Restaurant', nan], dtype=object)

In [493]:
merchants.risk_rating= merchants.risk_rating.str.strip()
# # merchants the white and space bar space
merchants['risk_rating'] = merchants['risk_rating'].str.replace("  ", " ")
merchants.risk_rating = merchants.risk_rating.str.title()
merchants.risk_rating.unique()

array(['Low', 'Medium', 'High', 'Critical', 'High Risk', nan, 'Unknown'],
      dtype=object)

In [494]:
# replacing null values with"Nan"
import numpy as np
merchants = merchants.replace(np.nan, "Nan")

In [495]:
merchants.isnull().sum()

merchant_id          0
merchant_name        0
merchant_category    0
province             0
city                 0
risk_rating          0
dtype: int64

In [496]:
# Showing the entire row duplicates
merchants.duplicated().sum()

# since the merchant id are unique
merchants['merchant_id'].duplicated().sum()

#viewing duplicates
merchants[merchants['merchant_id'].duplicated(keep=False)]

Empty DataFrame
Columns: [merchant_id, merchant_name, merchant_category, province, city, risk_rating]
Index: []

In [497]:
# Removing the duplicates
merchants = merchants.drop_duplicates()

merchants[merchants.duplicated() == True]

Empty DataFrame
Columns: [merchant_id, merchant_name, merchant_category, province, city, risk_rating]
Index: []

In [498]:
merchants.province = merchants.province.str.replace(r'\s+', ' ', regex=True)
merchants.province.unique()

array(['Free State', 'Mpumalanga', 'Limpopo', 'Kwazulu-Natal', 'Gauteng',
       'Eastern Cape', 'North West', 'Western Cape', 'Northern Cape'],
      dtype=object)

In [499]:
print(merchants.info())
print(merchants.isnull().sum())
print(merchants.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   merchant_id        20000 non-null  int64
 1   merchant_name      20000 non-null  object
 2   merchant_category  20000 non-null  object
 3   province           20000 non-null  object
 4   city               20000 non-null  object
 5   risk_rating        20000 non-null  object
dtypes: int64(1), object(5)
memory usage: 937.6+ KB
None
merchant_id          0
merchant_name        0
merchant_category    0
province             0
city                 0
risk_rating          0
dtype: int64
0

In [500]:
merchants.to_csv("data/processed/merchants_cleaned.csv")

# Date Feature Engineering

In [225]:
# Convert to datetime first
import pandas as pd

customers = pd.read_csv("data/processed/cleanedCustomers2.csv")
customers
#customers['transaction_date'] == pd.to_datetime(customers['transaction_date'])

,Unnamed: 0,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since
0,0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24
1,1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25
2,2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18
3,3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21
4,4,5,Emma,Molefe,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02
...,...,...,...,...,...,...,...,...,...,...
100085,100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03
100086,100390,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26
100087,100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28
100088,100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19
100089,100394,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17

In [226]:
#Converting customer_since data type to datetime and fixing date format
#customers['customer_since'] = customer['customer-since'].str.replace("-","/")

customers['customer_since'] = pd.to_datetime(customers['customer_since'],
format='mixed',
errors='coerce')

In [227]:
customers['Start_Year'] = customers.customer_since.dt.year
customers

,Unnamed: 0,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since,Start_Year
0,0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24,2022
1,1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25,2024
2,2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18,2020
3,3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21,2025
4,4,5,Emma,Molefe,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02,2013
...,...,...,...,...,...,...,...,...,...,...,...
100085,100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03,2025
100086,100390,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26,2016
100087,100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28,2021
100088,100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19,2016
100089,100394,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17,2013

In [228]:
customers['Start_Month'] = customers.customer_since.dt.month

In [229]:
customers['Start_Day'] = customers.customer_since.dt.day

In [230]:
customers['Weekday'] = customers.customer_since.dt.weekday
customers
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100090 entries, 0 to 100089
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         100090 non-null  int64
 1   customer_id        100090 non-null  int64
 2   first_name         100090 non-null  object
 3   last_name          100090 non-null  object
 4   age                100090 non-null  int64
 5   province           100090 non-null  object
 6   city               100090 non-null  object
 7   employment_status  100090 non-null  object
 8   income             100090 non-null  float64
 9   customer_since     100090 non-null  datetime64[ns]
 10  Start_Year         100090 non-null  int32
 11  Start_Month        100090 non-null  int32
 12  Start_Day          100090 non-null  int32
 13  Weekday            100090 non-null  int32
dtypes: datetime64[ns](1), float64(1), int32(4), int64(3), object(5)
memory usage: 9.2+ MB

In [231]:
customers

,Unnamed: 0,customer_id,first_name,last_name,age,province,city,employment_status,income,customer_since,Start_Year,Start_Month,Start_Day,Weekday
0,0,1,Emma,Naidoo,42,Free State,Bloemfontein,Employed,11418.82,2022-11-24,2022,11,24,3
1,1,2,Amelia,Mokoena,49,Mpumalanga,Mbombela,Nan,31336.45,2024-12-25,2024,12,25,2
2,2,3,Nomsa,Jacobs,34,North West,Rustenburg,Employed,11351.46,2020-03-18,2020,3,18,2
3,3,4,Sipho,Dlamini,35,Kwazulu-Natal,Durban,Retired,30291.15,2025-10-21,2025,10,21,1
4,4,5,Emma,Molefe,33,Kwazulu-Natal,Durban,Employed,28803.42,2013-10-02,2013,10,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100085,100388,40659,Sophia,Botha,39,Eastern Cape,Gqeberha,Employed,15477.05,2025-02-03,2025,2,3,0
100086,100390,93542,Noah,Jacobs,41,Gauteng,Johannesburg,Student,0.00,2016-12-26,2016,12,26,0
100087,100392,89556,Lerato,Botha,33,Kwazulu-Natal,Durban,Unemployed,21132.74,2021-08-28,2021,8,28,5
100088,100393,55437,Noah,Botha,56,Gauteng,Soweto,Retired,31652.89,2016-08-19,2016,8,19,4
100089,100394,85139,Noah,Mokoena,51,Eastern Cape,Mthatha,Employed,8714.87,2013-07-17,2013,7,17,2

# Fraud Features

In [2]:
import pandas as pd

In [233]:
accounts = pd.read_csv("data/processed/cleanedAccounts2.csv")
transactions = pd.read_csv("data/processed/transactions_clean.csv")

In [7]:
accounts = accounts.account_id.astype(str)

In [8]:
trans_acc = pd.merge(accounts,transactions, how='inner')

In [13]:
trans_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004012 entries, 0 to 1004011
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   account_id        1004012 non-null  object
 1   transaction_id    1004012 non-null  int64
 2   merchant_id       974290 non-null   object
 3   transaction_date  1004012 non-null  object
 4   transaction_type  1004012 non-null  object
 5   channel           992078 non-null   object
 6   amount            992006 non-null   object
 7   currency          1004012 non-null  object
 8   description       1004012 non-null  object
dtypes: int64(1), object(8)
memory usage: 68.9+ MB

In [ ]:
pd.DataFrame(trans_acc.groupby("account_id")['account_id'].count())
pd.DataFrame(trans_acc.groupby("account_id")['amount'].sum())

                                                       amount
account_id
1           8085.052029.01244.38102.31326.041463.251380.69...
10                      774.27R 477.7641.332035.74138.9889.98
100         232.814409.07798.263967.676594.35415.655659.51...
1000        377.863730.411798.16559.511754.261535.291176.9...
10000       561.321558.4103.7147.14947.861067.39439.811978...
...                                                       ...
99995       63.73123.39797.01202.42433.5532.79110.05513.52...
99996             33.24999.5407.91516.6242.592348.91588.790.0
99997       1423.312136.97785.59241.66961.27699.761332.433...
99998             295.451,8081708.33355.922630.79705.75111.82
99999       729.52544.43663.180.0389.742861.24187509.51255...

[124958 rows x 1 columns]